export interface Line {
  id: number
  name: string
  price: number
  stops: string[]
}

export const LINES: Line[] = [
  {
    id: 1,
    name: "Ligne 1",
    price: 1000,
    stops: [
      "Bingerville Nouvelle Gare",
      "Nouveau Goudron",
      "Cité Sir",
      "CHU Angré",
      "Carrefour prière",
      "SCIOMEX",
      "Stade Angré",
      "Carrefour Bluetooth",
      "Shell 7e tranche",
      "Carrefour Cascade",
    ],
  },
  {
    id: 2,
    name: "Ligne 2",
    price: 1000,
    stops: [
      "Bingerville Nouvelle Gare",
      "Freeworld Hôtel",
      "Carrefour AB Center",
      "Bon prix Faya",
      "Rond-point ancien camp",
      "Rond-point Mel Théodore",
      "Carrefour dame de la tendresse",
      "Saint Jean",
      "Carrefour La vie",
    ],
  },
  {
    id: 3,
    name: "Ligne 3",
    price: 600,
    stops: [
      "Bingerville Nouvelle Gare",
      "Nouveau Goudron",
      "Faya",
      "Carrefour ferronnerie",
      "MACI Canada",
      "Feu Pharmacie du bonheur",
      "Chez Samer",
      "Station Ola Palmeraie",
    ],
  },
  {
    id: 4,
    name: "Ligne 4",
    price: 700,
    stops: [
      "Station Ola Palmeraie",
      "Chez Samer Palmeraie",
      "Carrefour Guiraud",
      "Quick Market",
      "Rosiers Programme 2",
      "Pharmacie Vie de Grâce",
      "CGK",
      "Carrefour prière",
      "SCIOMEX",
      "Stade Angré",
      "Carrefour Bluetooth",
      "Station Shell 7e tranche",
      "Carrefour Cascade",
    ],
  },
  {
    id: 5,
    name: "Ligne 5",
    price: 1000,
    stops: [
      "Rond-point Rosiers Programme 3",
      "Rond-point 35e",
      "Rond-point Ado",
      "Sacré cœur",
      "Pharmacie Notre-Dame de l'incarnation",
      "Carrefour commissariat 9 Kilos",
      "Cap Nord",
      "Riviera 2",
      "École de police",
      "École de gendarmerie",
      "Cité des Arts",
      "RTI",
      "Saint Jean",
    ],
  },
  {
    id: 6,
    name: "Ligne 6",
    price: 1000,
    stops: [
      "Angré Carrefour Cabri",
      "Angré Fin goudron",
      "Pharmacie des Allées",
      "Terminus 8B/2",
      "Pétro Ivoire",
      "22e arrondissement",
      "Carrefour Opéra",
      "Las Palmas",
      "Carrefour Mobile",
      "ENA",
      "Carrefour La vie",
      "RTI",
      "Saint Jean",
    ],
  },
  {
    id: 7,
    name: "Ligne 7",
    price: 700,
    stops: [
      "Angré Carrefour Cabri",
      "Angré Fin goudron",
      "Angré Château",
      "Lycée Angré",
      "Groupement 4000 D",
      "SNEAD Angré",
      "Terminus 8B/2",
      "Carrefour Bluetooth",
      "Shell 7e tranche",
      "Carrefour Cascade",
    ],
  },
  {
    id: 8,
    name: "Ligne 8",
    price: 1000,
    stops: [
      "Angré Carrefour Cabri",
      "Angré Fin goudron",
      "Angré Château",
      "Lycée Angré",
      "Groupement 4000 D",
      "SNEAD Angré",
      "Terminus 8B/2",
      "Carrefour Bluetooth",
      "Shell 7e tranche",
      "Carrefour Cascade",
      "30e arrondissement",
      "Pharmacie St Bernard",
      "Doraville",
      "Pharmacie St Ange",
      "André Malraux",
    ],
  },
]

export const COMMUNES = [
  "Abobo",
  "Adjamé",
  "Angré",
  "Attécoubé",
  "Bingerville",
  "Cocody",
  "Koumassi",
  "Marcory",
  "Plateau",
  "Port-Bouët",
  "Treichville",
  "Yopougon",
]
